// Code generated by BobGen sql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var InputFiles = Table[
	inputFileColumns,
	inputFileIndexes,
	inputFileForeignKeys,
	inputFileUniques,
	inputFileChecks,
]{
	Schema: "",
	Name:   "input_files",
	Columns: inputFileColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "IDENTITY",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Bucket: column{
			Name:      "bucket",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ObjectKey: column{
			Name:      "object_key",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		URI: column{
			Name:      "uri",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Format: column{
			Name:      "format",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ContentType: column{
			Name:      "content_type",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		SizeBytes: column{
			Name:      "size_bytes",
			DBType:    "bigint",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Etag: column{
			Name:      "etag",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Metadata: column{
			Name:      "metadata",
			DBType:    "jsonb",
			Default:   "'{}'::jsonb",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: inputFileIndexes{
		InputFilesPkey: index{
			Type: "btree",
			Name: "input_files_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		InputFilesBucketObjectKeyUnique: index{
			Type: "btree",
			Name: "input_files_bucket_object_key_unique",
			Columns: []indexColumn{
				{
					Name:         "bucket",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "object_key",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false, false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		InputFilesURIUnique: index{
			Type: "btree",
			Name: "input_files_uri_unique",
			Columns: []indexColumn{
				{
					Name:         "uri",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "input_files_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: inputFileUniques{
		InputFilesBucketObjectKeyUnique: constraint{
			Name:    "input_files_bucket_object_key_unique",
			Columns: []string{"bucket", "object_key"},
			Comment: "",
		},
		InputFilesURIUnique: constraint{
			Name:    "input_files_uri_unique",
			Columns: []string{"uri"},
			Comment: "",
		},
	},
	Checks: inputFileChecks{
		InputFilesFormatCheck: check{
			constraint: constraint{
				Name:    "input_files_format_check",
				Columns: []string{"format"},
				Comment: "",
			},
			Expression: "(format = ANY (ARRAY['csv'::text, 'parquet'::text]))",
		},
	},
	Comment: "",
}

type inputFileColumns struct {
	ID          column
	Name        column
	Bucket      column
	ObjectKey   column
	URI         column
	Format      column
	ContentType column
	SizeBytes   column
	Etag        column
	Metadata    column
	CreatedAt   column
	UpdatedAt   column
}

func (c inputFileColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.Bucket, c.ObjectKey, c.URI, c.Format, c.ContentType, c.SizeBytes, c.Etag, c.Metadata, c.CreatedAt, c.UpdatedAt,
	}
}

type inputFileIndexes struct {
	InputFilesPkey                  index
	InputFilesBucketObjectKeyUnique index
	InputFilesURIUnique             index
}

func (i inputFileIndexes) AsSlice() []index {
	return []index{
		i.InputFilesPkey, i.InputFilesBucketObjectKeyUnique, i.InputFilesURIUnique,
	}
}

type inputFileForeignKeys struct{}

func (f inputFileForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type inputFileUniques struct {
	InputFilesBucketObjectKeyUnique constraint
	InputFilesURIUnique             constraint
}

func (u inputFileUniques) AsSlice() []constraint {
	return []constraint{
		u.InputFilesBucketObjectKeyUnique, u.InputFilesURIUnique,
	}
}

type inputFileChecks struct {
	InputFilesFormatCheck check
}

func (c inputFileChecks) AsSlice() []check {
	return []check{
		c.InputFilesFormatCheck,
	}
}
