// Code generated by BobGen sql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Pipelines = Table[
	pipelineColumns,
	pipelineIndexes,
	pipelineForeignKeys,
	pipelineUniques,
	pipelineChecks,
]{
	Schema: "",
	Name:   "pipelines",
	Columns: pipelineColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "IDENTITY",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		PipelineID: column{
			Name:      "pipeline_id",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Version: column{
			Name:      "version",
			DBType:    "integer",
			Default:   "1",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Spec: column{
			Name:      "spec",
			DBType:    "jsonb",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Status: column{
			Name:      "status",
			DBType:    "text",
			Default:   "'draft'::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ValidationError: column{
			Name:      "validation_error",
			DBType:    "jsonb",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		ActivatedAt: column{
			Name:      "activated_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: pipelineIndexes{
		PipelinesPkey: index{
			Type: "btree",
			Name: "pipelines_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		PipelinesPipelineIDUnique: index{
			Type: "btree",
			Name: "pipelines_pipeline_id_unique",
			Columns: []indexColumn{
				{
					Name:         "pipeline_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "pipelines_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: pipelineUniques{
		PipelinesPipelineIDUnique: constraint{
			Name:    "pipelines_pipeline_id_unique",
			Columns: []string{"pipeline_id"},
			Comment: "",
		},
	},
	Checks: pipelineChecks{
		PipelinesStatusCheck: check{
			constraint: constraint{
				Name:    "pipelines_status_check",
				Columns: []string{"status"},
				Comment: "",
			},
			Expression: "(status = ANY (ARRAY['draft'::text, 'active'::text]))",
		},
	},
	Comment: "",
}

type pipelineColumns struct {
	ID              column
	Name            column
	PipelineID      column
	Version         column
	Spec            column
	Status          column
	ValidationError column
	ActivatedAt     column
	CreatedAt       column
	UpdatedAt       column
}

func (c pipelineColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.PipelineID, c.Version, c.Spec, c.Status, c.ValidationError, c.ActivatedAt, c.CreatedAt, c.UpdatedAt,
	}
}

type pipelineIndexes struct {
	PipelinesPkey             index
	PipelinesPipelineIDUnique index
}

func (i pipelineIndexes) AsSlice() []index {
	return []index{
		i.PipelinesPkey, i.PipelinesPipelineIDUnique,
	}
}

type pipelineForeignKeys struct{}

func (f pipelineForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type pipelineUniques struct {
	PipelinesPipelineIDUnique constraint
}

func (u pipelineUniques) AsSlice() []constraint {
	return []constraint{
		u.PipelinesPipelineIDUnique,
	}
}

type pipelineChecks struct {
	PipelinesStatusCheck check
}

func (c pipelineChecks) AsSlice() []check {
	return []check{
		c.PipelinesStatusCheck,
	}
}
