// Code generated by BobGen sql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var StubRecords = Table[
	stubRecordColumns,
	stubRecordIndexes,
	stubRecordForeignKeys,
	stubRecordUniques,
	stubRecordChecks,
]{
	Schema: "",
	Name:   "stub_records",
	Columns: stubRecordColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "IDENTITY",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: stubRecordIndexes{
		StubRecordsPkey: index{
			Type: "btree",
			Name: "stub_records_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "stub_records_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type stubRecordColumns struct {
	ID        column
	Name      column
	CreatedAt column
}

func (c stubRecordColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.CreatedAt,
	}
}

type stubRecordIndexes struct {
	StubRecordsPkey index
}

func (i stubRecordIndexes) AsSlice() []index {
	return []index{
		i.StubRecordsPkey,
	}
}

type stubRecordForeignKeys struct{}

func (f stubRecordForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type stubRecordUniques struct{}

func (u stubRecordUniques) AsSlice() []constraint {
	return []constraint{}
}

type stubRecordChecks struct{}

func (c stubRecordChecks) AsSlice() []check {
	return []check{}
}
