// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/stephenafamo/bob/types"
	models "go-transformer/internal/db/models"
)

type Factory struct {
	baseInputFileMods InputFileModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewInputFile(mods ...InputFileMod) *InputFileTemplate {
	return f.NewInputFileWithContext(context.Background(), mods...)
}

func (f *Factory) NewInputFileWithContext(ctx context.Context, mods ...InputFileMod) *InputFileTemplate {
	o := &InputFileTemplate{f: f}

	if f != nil {
		f.baseInputFileMods.Apply(ctx, o)
	}

	InputFileModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingInputFile(m *models.InputFile) *InputFileTemplate {
	o := &InputFileTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Name = func() string { return m.Name }
	o.Bucket = func() string { return m.Bucket }
	o.ObjectKey = func() string { return m.ObjectKey }
	o.URI = func() string { return m.URI }
	o.Format = func() string { return m.Format }
	o.ContentType = func() sql.Null[string] { return m.ContentType }
	o.SizeBytes = func() int64 { return m.SizeBytes }
	o.Etag = func() sql.Null[string] { return m.Etag }
	o.Metadata = func() types.JSON[json.RawMessage] { return m.Metadata }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	return o
}

func (f *Factory) ClearBaseInputFileMods() {
	f.baseInputFileMods = nil
}

func (f *Factory) AddBaseInputFileMod(mods ...InputFileMod) {
	f.baseInputFileMods = append(f.baseInputFileMods, mods...)
}
