// Code generated by BobGen sql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	models "go-transformer/internal/db/models"
)

type Factory struct {
	baseStubRecordMods StubRecordModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewStubRecord(mods ...StubRecordMod) *StubRecordTemplate {
	return f.NewStubRecordWithContext(context.Background(), mods...)
}

func (f *Factory) NewStubRecordWithContext(ctx context.Context, mods ...StubRecordMod) *StubRecordTemplate {
	o := &StubRecordTemplate{f: f}

	if f != nil {
		f.baseStubRecordMods.Apply(ctx, o)
	}

	StubRecordModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingStubRecord(m *models.StubRecord) *StubRecordTemplate {
	o := &StubRecordTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Name = func() string { return m.Name }
	o.CreatedAt = func() time.Time { return m.CreatedAt }

	return o
}

func (f *Factory) ClearBaseStubRecordMods() {
	f.baseStubRecordMods = nil
}

func (f *Factory) AddBaseStubRecordMod(mods ...StubRecordMod) {
	f.baseStubRecordMods = append(f.baseStubRecordMods, mods...)
}
