// Code generated by BobGen sql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/stephenafamo/bob/types"
	models "go-transformer/internal/db/models"
)

type Factory struct {
	baseInputFileMods InputFileModSlice
	basePipelineMods  PipelineModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewInputFile(mods ...InputFileMod) *InputFileTemplate {
	return f.NewInputFileWithContext(context.Background(), mods...)
}

func (f *Factory) NewInputFileWithContext(ctx context.Context, mods ...InputFileMod) *InputFileTemplate {
	o := &InputFileTemplate{f: f}

	if f != nil {
		f.baseInputFileMods.Apply(ctx, o)
	}

	InputFileModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingInputFile(m *models.InputFile) *InputFileTemplate {
	o := &InputFileTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Name = func() string { return m.Name }
	o.Bucket = func() string { return m.Bucket }
	o.ObjectKey = func() string { return m.ObjectKey }
	o.URI = func() string { return m.URI }
	o.Format = func() string { return m.Format }
	o.ContentType = func() sql.Null[string] { return m.ContentType }
	o.SizeBytes = func() int64 { return m.SizeBytes }
	o.Etag = func() sql.Null[string] { return m.Etag }
	o.Metadata = func() types.JSON[json.RawMessage] { return m.Metadata }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	return o
}

func (f *Factory) NewPipeline(mods ...PipelineMod) *PipelineTemplate {
	return f.NewPipelineWithContext(context.Background(), mods...)
}

func (f *Factory) NewPipelineWithContext(ctx context.Context, mods ...PipelineMod) *PipelineTemplate {
	o := &PipelineTemplate{f: f}

	if f != nil {
		f.basePipelineMods.Apply(ctx, o)
	}

	PipelineModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingPipeline(m *models.Pipeline) *PipelineTemplate {
	o := &PipelineTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Name = func() string { return m.Name }
	o.PipelineID = func() string { return m.PipelineID }
	o.Version = func() int32 { return m.Version }
	o.Spec = func() types.JSON[json.RawMessage] { return m.Spec }
	o.Status = func() string { return m.Status }
	o.ValidationError = func() sql.Null[types.JSON[json.RawMessage]] { return m.ValidationError }
	o.ActivatedAt = func() sql.Null[time.Time] { return m.ActivatedAt }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	return o
}

func (f *Factory) ClearBaseInputFileMods() {
	f.baseInputFileMods = nil
}

func (f *Factory) AddBaseInputFileMod(mods ...InputFileMod) {
	f.baseInputFileMods = append(f.baseInputFileMods, mods...)
}

func (f *Factory) ClearBasePipelineMods() {
	f.basePipelineMods = nil
}

func (f *Factory) AddBasePipelineMod(mods ...PipelineMod) {
	f.basePipelineMods = append(f.basePipelineMods, mods...)
}
