// Code generated by BobGen sql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"database/sql"
	"encoding/json"
	"testing"
	"time"

	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
	models "go-transformer/internal/db/models"
)

type InputFileMod interface {
	Apply(context.Context, *InputFileTemplate)
}

type InputFileModFunc func(context.Context, *InputFileTemplate)

func (f InputFileModFunc) Apply(ctx context.Context, n *InputFileTemplate) {
	f(ctx, n)
}

type InputFileModSlice []InputFileMod

func (mods InputFileModSlice) Apply(ctx context.Context, n *InputFileTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// InputFileTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type InputFileTemplate struct {
	ID          func() int64
	Name        func() string
	Bucket      func() string
	ObjectKey   func() string
	URI         func() string
	Format      func() string
	ContentType func() sql.Null[string]
	SizeBytes   func() int64
	Etag        func() sql.Null[string]
	Metadata    func() types.JSON[json.RawMessage]
	CreatedAt   func() time.Time
	UpdatedAt   func() time.Time

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the InputFileTemplate
func (o *InputFileTemplate) Apply(ctx context.Context, mods ...InputFileMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.InputFile
// according to the relationships in the template. Nothing is inserted into the db
func (t InputFileTemplate) setModelRels(o *models.InputFile) {}

// BuildSetter returns an *models.InputFileSetter
// this does nothing with the relationship templates
func (o InputFileTemplate) BuildSetter() *models.InputFileSetter {
	m := &models.InputFileSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = func() *int64 { return &val }()
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = func() *string { return &val }()
	}
	if o.Bucket != nil {
		val := o.Bucket()
		m.Bucket = func() *string { return &val }()
	}
	if o.ObjectKey != nil {
		val := o.ObjectKey()
		m.ObjectKey = func() *string { return &val }()
	}
	if o.URI != nil {
		val := o.URI()
		m.URI = func() *string { return &val }()
	}
	if o.Format != nil {
		val := o.Format()
		m.Format = func() *string { return &val }()
	}
	if o.ContentType != nil {
		val := o.ContentType()
		m.ContentType = func() *sql.Null[string] { v := val; return &v }()
	}
	if o.SizeBytes != nil {
		val := o.SizeBytes()
		m.SizeBytes = func() *int64 { return &val }()
	}
	if o.Etag != nil {
		val := o.Etag()
		m.Etag = func() *sql.Null[string] { v := val; return &v }()
	}
	if o.Metadata != nil {
		val := o.Metadata()
		m.Metadata = func() *types.JSON[json.RawMessage] { return &val }()
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = func() *time.Time { return &val }()
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = func() *time.Time { return &val }()
	}

	return m
}

// BuildManySetter returns an []*models.InputFileSetter
// this does nothing with the relationship templates
func (o InputFileTemplate) BuildManySetter(number int) []*models.InputFileSetter {
	m := make([]*models.InputFileSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.InputFile
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use InputFileTemplate.Create
func (o InputFileTemplate) Build() *models.InputFile {
	m := &models.InputFile{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Bucket != nil {
		m.Bucket = o.Bucket()
	}
	if o.ObjectKey != nil {
		m.ObjectKey = o.ObjectKey()
	}
	if o.URI != nil {
		m.URI = o.URI()
	}
	if o.Format != nil {
		m.Format = o.Format()
	}
	if o.ContentType != nil {
		m.ContentType = o.ContentType()
	}
	if o.SizeBytes != nil {
		m.SizeBytes = o.SizeBytes()
	}
	if o.Etag != nil {
		m.Etag = o.Etag()
	}
	if o.Metadata != nil {
		m.Metadata = o.Metadata()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.InputFileSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use InputFileTemplate.CreateMany
func (o InputFileTemplate) BuildMany(number int) models.InputFileSlice {
	m := make(models.InputFileSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableInputFile(m *models.InputFileSetter) {
	if !(m.Name != nil) {
		val := random_string(nil)
		m.Name = func() *string { return &val }()
	}
	if !(m.Bucket != nil) {
		val := random_string(nil)
		m.Bucket = func() *string { return &val }()
	}
	if !(m.ObjectKey != nil) {
		val := random_string(nil)
		m.ObjectKey = func() *string { return &val }()
	}
	if !(m.URI != nil) {
		val := random_string(nil)
		m.URI = func() *string { return &val }()
	}
	if !(m.Format != nil) {
		val := random_string(nil)
		m.Format = func() *string { return &val }()
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.InputFile
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *InputFileTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.InputFile) error {
	var err error

	return err
}

// Create builds a inputFile and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *InputFileTemplate) Create(ctx context.Context, exec bob.Executor) (*models.InputFile, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableInputFile(opt)

	m, err := models.InputFiles.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a inputFile and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *InputFileTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.InputFile {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a inputFile and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *InputFileTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.InputFile {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple inputFiles and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o InputFileTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.InputFileSlice, error) {
	var err error
	m := make(models.InputFileSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple inputFiles and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o InputFileTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.InputFileSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple inputFiles and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o InputFileTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.InputFileSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// InputFile has methods that act as mods for the InputFileTemplate
var InputFileMods inputFileMods

type inputFileMods struct{}

func (m inputFileMods) RandomizeAllColumns(f *faker.Faker) InputFileMod {
	return InputFileModSlice{
		InputFileMods.RandomID(f),
		InputFileMods.RandomName(f),
		InputFileMods.RandomBucket(f),
		InputFileMods.RandomObjectKey(f),
		InputFileMods.RandomURI(f),
		InputFileMods.RandomFormat(f),
		InputFileMods.RandomContentType(f),
		InputFileMods.RandomSizeBytes(f),
		InputFileMods.RandomEtag(f),
		InputFileMods.RandomMetadata(f),
		InputFileMods.RandomCreatedAt(f),
		InputFileMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m inputFileMods) ID(val int64) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m inputFileMods) IDFunc(f func() int64) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m inputFileMods) UnsetID() InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m inputFileMods) RandomID(f *faker.Faker) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m inputFileMods) Name(val string) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m inputFileMods) NameFunc(f func() string) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m inputFileMods) UnsetName() InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m inputFileMods) RandomName(f *faker.Faker) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m inputFileMods) Bucket(val string) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Bucket = func() string { return val }
	})
}

// Set the Column from the function
func (m inputFileMods) BucketFunc(f func() string) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Bucket = f
	})
}

// Clear any values for the column
func (m inputFileMods) UnsetBucket() InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Bucket = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m inputFileMods) RandomBucket(f *faker.Faker) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Bucket = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m inputFileMods) ObjectKey(val string) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.ObjectKey = func() string { return val }
	})
}

// Set the Column from the function
func (m inputFileMods) ObjectKeyFunc(f func() string) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.ObjectKey = f
	})
}

// Clear any values for the column
func (m inputFileMods) UnsetObjectKey() InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.ObjectKey = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m inputFileMods) RandomObjectKey(f *faker.Faker) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.ObjectKey = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m inputFileMods) URI(val string) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.URI = func() string { return val }
	})
}

// Set the Column from the function
func (m inputFileMods) URIFunc(f func() string) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.URI = f
	})
}

// Clear any values for the column
func (m inputFileMods) UnsetURI() InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.URI = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m inputFileMods) RandomURI(f *faker.Faker) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.URI = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m inputFileMods) Format(val string) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Format = func() string { return val }
	})
}

// Set the Column from the function
func (m inputFileMods) FormatFunc(f func() string) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Format = f
	})
}

// Clear any values for the column
func (m inputFileMods) UnsetFormat() InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Format = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m inputFileMods) RandomFormat(f *faker.Faker) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Format = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m inputFileMods) ContentType(val sql.Null[string]) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.ContentType = func() sql.Null[string] { return val }
	})
}

// Set the Column from the function
func (m inputFileMods) ContentTypeFunc(f func() sql.Null[string]) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.ContentType = f
	})
}

// Clear any values for the column
func (m inputFileMods) UnsetContentType() InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.ContentType = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m inputFileMods) RandomContentType(f *faker.Faker) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.ContentType = func() sql.Null[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return sql.Null[string]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m inputFileMods) RandomContentTypeNotNull(f *faker.Faker) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.ContentType = func() sql.Null[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return sql.Null[string]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m inputFileMods) SizeBytes(val int64) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.SizeBytes = func() int64 { return val }
	})
}

// Set the Column from the function
func (m inputFileMods) SizeBytesFunc(f func() int64) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.SizeBytes = f
	})
}

// Clear any values for the column
func (m inputFileMods) UnsetSizeBytes() InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.SizeBytes = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m inputFileMods) RandomSizeBytes(f *faker.Faker) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.SizeBytes = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m inputFileMods) Etag(val sql.Null[string]) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Etag = func() sql.Null[string] { return val }
	})
}

// Set the Column from the function
func (m inputFileMods) EtagFunc(f func() sql.Null[string]) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Etag = f
	})
}

// Clear any values for the column
func (m inputFileMods) UnsetEtag() InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Etag = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m inputFileMods) RandomEtag(f *faker.Faker) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Etag = func() sql.Null[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return sql.Null[string]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m inputFileMods) RandomEtagNotNull(f *faker.Faker) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Etag = func() sql.Null[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return sql.Null[string]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m inputFileMods) Metadata(val types.JSON[json.RawMessage]) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Metadata = func() types.JSON[json.RawMessage] { return val }
	})
}

// Set the Column from the function
func (m inputFileMods) MetadataFunc(f func() types.JSON[json.RawMessage]) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Metadata = f
	})
}

// Clear any values for the column
func (m inputFileMods) UnsetMetadata() InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Metadata = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m inputFileMods) RandomMetadata(f *faker.Faker) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.Metadata = func() types.JSON[json.RawMessage] {
			return random_types_JSON_json_RawMessage_(f)
		}
	})
}

// Set the model columns to this value
func (m inputFileMods) CreatedAt(val time.Time) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m inputFileMods) CreatedAtFunc(f func() time.Time) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m inputFileMods) UnsetCreatedAt() InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m inputFileMods) RandomCreatedAt(f *faker.Faker) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m inputFileMods) UpdatedAt(val time.Time) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m inputFileMods) UpdatedAtFunc(f func() time.Time) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m inputFileMods) UnsetUpdatedAt() InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m inputFileMods) RandomUpdatedAt(f *faker.Faker) InputFileMod {
	return InputFileModFunc(func(_ context.Context, o *InputFileTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m inputFileMods) WithParentsCascading() InputFileMod {
	return InputFileModFunc(func(ctx context.Context, o *InputFileTemplate) {
		if isDone, _ := inputFileWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = inputFileWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
