// Code generated by BobGen sql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"database/sql"
	"encoding/json"
	"testing"
	"time"

	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
	models "go-transformer/internal/db/models"
)

type PipelineMod interface {
	Apply(context.Context, *PipelineTemplate)
}

type PipelineModFunc func(context.Context, *PipelineTemplate)

func (f PipelineModFunc) Apply(ctx context.Context, n *PipelineTemplate) {
	f(ctx, n)
}

type PipelineModSlice []PipelineMod

func (mods PipelineModSlice) Apply(ctx context.Context, n *PipelineTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// PipelineTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type PipelineTemplate struct {
	ID              func() int64
	Name            func() string
	PipelineID      func() string
	Version         func() int32
	Spec            func() types.JSON[json.RawMessage]
	Status          func() string
	ValidationError func() sql.Null[types.JSON[json.RawMessage]]
	ActivatedAt     func() sql.Null[time.Time]
	CreatedAt       func() time.Time
	UpdatedAt       func() time.Time

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the PipelineTemplate
func (o *PipelineTemplate) Apply(ctx context.Context, mods ...PipelineMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Pipeline
// according to the relationships in the template. Nothing is inserted into the db
func (t PipelineTemplate) setModelRels(o *models.Pipeline) {}

// BuildSetter returns an *models.PipelineSetter
// this does nothing with the relationship templates
func (o PipelineTemplate) BuildSetter() *models.PipelineSetter {
	m := &models.PipelineSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = func() *int64 { return &val }()
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = func() *string { return &val }()
	}
	if o.PipelineID != nil {
		val := o.PipelineID()
		m.PipelineID = func() *string { return &val }()
	}
	if o.Version != nil {
		val := o.Version()
		m.Version = func() *int32 { return &val }()
	}
	if o.Spec != nil {
		val := o.Spec()
		m.Spec = func() *types.JSON[json.RawMessage] { return &val }()
	}
	if o.Status != nil {
		val := o.Status()
		m.Status = func() *string { return &val }()
	}
	if o.ValidationError != nil {
		val := o.ValidationError()
		m.ValidationError = func() *sql.Null[types.JSON[json.RawMessage]] { v := val; return &v }()
	}
	if o.ActivatedAt != nil {
		val := o.ActivatedAt()
		m.ActivatedAt = func() *sql.Null[time.Time] { v := val; return &v }()
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = func() *time.Time { return &val }()
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = func() *time.Time { return &val }()
	}

	return m
}

// BuildManySetter returns an []*models.PipelineSetter
// this does nothing with the relationship templates
func (o PipelineTemplate) BuildManySetter(number int) []*models.PipelineSetter {
	m := make([]*models.PipelineSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Pipeline
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use PipelineTemplate.Create
func (o PipelineTemplate) Build() *models.Pipeline {
	m := &models.Pipeline{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.PipelineID != nil {
		m.PipelineID = o.PipelineID()
	}
	if o.Version != nil {
		m.Version = o.Version()
	}
	if o.Spec != nil {
		m.Spec = o.Spec()
	}
	if o.Status != nil {
		m.Status = o.Status()
	}
	if o.ValidationError != nil {
		m.ValidationError = o.ValidationError()
	}
	if o.ActivatedAt != nil {
		m.ActivatedAt = o.ActivatedAt()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.PipelineSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use PipelineTemplate.CreateMany
func (o PipelineTemplate) BuildMany(number int) models.PipelineSlice {
	m := make(models.PipelineSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatablePipeline(m *models.PipelineSetter) {
	if !(m.Name != nil) {
		val := random_string(nil)
		m.Name = func() *string { return &val }()
	}
	if !(m.PipelineID != nil) {
		val := random_string(nil)
		m.PipelineID = func() *string { return &val }()
	}
	if !(m.Spec != nil) {
		val := random_types_JSON_json_RawMessage_(nil)
		m.Spec = func() *types.JSON[json.RawMessage] { return &val }()
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Pipeline
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *PipelineTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Pipeline) error {
	var err error

	return err
}

// Create builds a pipeline and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *PipelineTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Pipeline, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatablePipeline(opt)

	m, err := models.Pipelines.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a pipeline and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *PipelineTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Pipeline {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a pipeline and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *PipelineTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Pipeline {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple pipelines and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o PipelineTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.PipelineSlice, error) {
	var err error
	m := make(models.PipelineSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple pipelines and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o PipelineTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.PipelineSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple pipelines and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o PipelineTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.PipelineSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Pipeline has methods that act as mods for the PipelineTemplate
var PipelineMods pipelineMods

type pipelineMods struct{}

func (m pipelineMods) RandomizeAllColumns(f *faker.Faker) PipelineMod {
	return PipelineModSlice{
		PipelineMods.RandomID(f),
		PipelineMods.RandomName(f),
		PipelineMods.RandomPipelineID(f),
		PipelineMods.RandomVersion(f),
		PipelineMods.RandomSpec(f),
		PipelineMods.RandomStatus(f),
		PipelineMods.RandomValidationError(f),
		PipelineMods.RandomActivatedAt(f),
		PipelineMods.RandomCreatedAt(f),
		PipelineMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m pipelineMods) ID(val int64) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m pipelineMods) IDFunc(f func() int64) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m pipelineMods) UnsetID() PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m pipelineMods) RandomID(f *faker.Faker) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m pipelineMods) Name(val string) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m pipelineMods) NameFunc(f func() string) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m pipelineMods) UnsetName() PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m pipelineMods) RandomName(f *faker.Faker) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m pipelineMods) PipelineID(val string) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.PipelineID = func() string { return val }
	})
}

// Set the Column from the function
func (m pipelineMods) PipelineIDFunc(f func() string) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.PipelineID = f
	})
}

// Clear any values for the column
func (m pipelineMods) UnsetPipelineID() PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.PipelineID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m pipelineMods) RandomPipelineID(f *faker.Faker) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.PipelineID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m pipelineMods) Version(val int32) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.Version = func() int32 { return val }
	})
}

// Set the Column from the function
func (m pipelineMods) VersionFunc(f func() int32) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.Version = f
	})
}

// Clear any values for the column
func (m pipelineMods) UnsetVersion() PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.Version = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m pipelineMods) RandomVersion(f *faker.Faker) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.Version = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m pipelineMods) Spec(val types.JSON[json.RawMessage]) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.Spec = func() types.JSON[json.RawMessage] { return val }
	})
}

// Set the Column from the function
func (m pipelineMods) SpecFunc(f func() types.JSON[json.RawMessage]) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.Spec = f
	})
}

// Clear any values for the column
func (m pipelineMods) UnsetSpec() PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.Spec = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m pipelineMods) RandomSpec(f *faker.Faker) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.Spec = func() types.JSON[json.RawMessage] {
			return random_types_JSON_json_RawMessage_(f)
		}
	})
}

// Set the model columns to this value
func (m pipelineMods) Status(val string) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.Status = func() string { return val }
	})
}

// Set the Column from the function
func (m pipelineMods) StatusFunc(f func() string) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.Status = f
	})
}

// Clear any values for the column
func (m pipelineMods) UnsetStatus() PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.Status = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m pipelineMods) RandomStatus(f *faker.Faker) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.Status = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m pipelineMods) ValidationError(val sql.Null[types.JSON[json.RawMessage]]) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.ValidationError = func() sql.Null[types.JSON[json.RawMessage]] { return val }
	})
}

// Set the Column from the function
func (m pipelineMods) ValidationErrorFunc(f func() sql.Null[types.JSON[json.RawMessage]]) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.ValidationError = f
	})
}

// Clear any values for the column
func (m pipelineMods) UnsetValidationError() PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.ValidationError = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m pipelineMods) RandomValidationError(f *faker.Faker) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.ValidationError = func() sql.Null[types.JSON[json.RawMessage]] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_types_JSON_json_RawMessage_(f)
			return sql.Null[types.JSON[json.RawMessage]]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m pipelineMods) RandomValidationErrorNotNull(f *faker.Faker) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.ValidationError = func() sql.Null[types.JSON[json.RawMessage]] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_types_JSON_json_RawMessage_(f)
			return sql.Null[types.JSON[json.RawMessage]]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m pipelineMods) ActivatedAt(val sql.Null[time.Time]) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.ActivatedAt = func() sql.Null[time.Time] { return val }
	})
}

// Set the Column from the function
func (m pipelineMods) ActivatedAtFunc(f func() sql.Null[time.Time]) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.ActivatedAt = f
	})
}

// Clear any values for the column
func (m pipelineMods) UnsetActivatedAt() PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.ActivatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m pipelineMods) RandomActivatedAt(f *faker.Faker) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.ActivatedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m pipelineMods) RandomActivatedAtNotNull(f *faker.Faker) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.ActivatedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m pipelineMods) CreatedAt(val time.Time) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m pipelineMods) CreatedAtFunc(f func() time.Time) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m pipelineMods) UnsetCreatedAt() PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m pipelineMods) RandomCreatedAt(f *faker.Faker) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m pipelineMods) UpdatedAt(val time.Time) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m pipelineMods) UpdatedAtFunc(f func() time.Time) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m pipelineMods) UnsetUpdatedAt() PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m pipelineMods) RandomUpdatedAt(f *faker.Faker) PipelineMod {
	return PipelineModFunc(func(_ context.Context, o *PipelineTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m pipelineMods) WithParentsCascading() PipelineMod {
	return PipelineModFunc(func(ctx context.Context, o *PipelineTemplate) {
		if isDone, _ := pipelineWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = pipelineWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
