// Code generated by BobGen sql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	models "go-transformer/internal/db/models"
)

type StubRecordMod interface {
	Apply(context.Context, *StubRecordTemplate)
}

type StubRecordModFunc func(context.Context, *StubRecordTemplate)

func (f StubRecordModFunc) Apply(ctx context.Context, n *StubRecordTemplate) {
	f(ctx, n)
}

type StubRecordModSlice []StubRecordMod

func (mods StubRecordModSlice) Apply(ctx context.Context, n *StubRecordTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// StubRecordTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type StubRecordTemplate struct {
	ID        func() int64
	Name      func() string
	CreatedAt func() time.Time

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the StubRecordTemplate
func (o *StubRecordTemplate) Apply(ctx context.Context, mods ...StubRecordMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.StubRecord
// according to the relationships in the template. Nothing is inserted into the db
func (t StubRecordTemplate) setModelRels(o *models.StubRecord) {}

// BuildSetter returns an *models.StubRecordSetter
// this does nothing with the relationship templates
func (o StubRecordTemplate) BuildSetter() *models.StubRecordSetter {
	m := &models.StubRecordSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = func() *int64 { return &val }()
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = func() *string { return &val }()
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = func() *time.Time { return &val }()
	}

	return m
}

// BuildManySetter returns an []*models.StubRecordSetter
// this does nothing with the relationship templates
func (o StubRecordTemplate) BuildManySetter(number int) []*models.StubRecordSetter {
	m := make([]*models.StubRecordSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.StubRecord
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use StubRecordTemplate.Create
func (o StubRecordTemplate) Build() *models.StubRecord {
	m := &models.StubRecord{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.StubRecordSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use StubRecordTemplate.CreateMany
func (o StubRecordTemplate) BuildMany(number int) models.StubRecordSlice {
	m := make(models.StubRecordSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableStubRecord(m *models.StubRecordSetter) {
	if !(m.Name != nil) {
		val := random_string(nil)
		m.Name = func() *string { return &val }()
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.StubRecord
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *StubRecordTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.StubRecord) error {
	var err error

	return err
}

// Create builds a stubRecord and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *StubRecordTemplate) Create(ctx context.Context, exec bob.Executor) (*models.StubRecord, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableStubRecord(opt)

	m, err := models.StubRecords.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a stubRecord and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *StubRecordTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.StubRecord {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a stubRecord and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *StubRecordTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.StubRecord {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple stubRecords and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o StubRecordTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.StubRecordSlice, error) {
	var err error
	m := make(models.StubRecordSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple stubRecords and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o StubRecordTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.StubRecordSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple stubRecords and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o StubRecordTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.StubRecordSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// StubRecord has methods that act as mods for the StubRecordTemplate
var StubRecordMods stubRecordMods

type stubRecordMods struct{}

func (m stubRecordMods) RandomizeAllColumns(f *faker.Faker) StubRecordMod {
	return StubRecordModSlice{
		StubRecordMods.RandomID(f),
		StubRecordMods.RandomName(f),
		StubRecordMods.RandomCreatedAt(f),
	}
}

// Set the model columns to this value
func (m stubRecordMods) ID(val int64) StubRecordMod {
	return StubRecordModFunc(func(_ context.Context, o *StubRecordTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m stubRecordMods) IDFunc(f func() int64) StubRecordMod {
	return StubRecordModFunc(func(_ context.Context, o *StubRecordTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m stubRecordMods) UnsetID() StubRecordMod {
	return StubRecordModFunc(func(_ context.Context, o *StubRecordTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m stubRecordMods) RandomID(f *faker.Faker) StubRecordMod {
	return StubRecordModFunc(func(_ context.Context, o *StubRecordTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m stubRecordMods) Name(val string) StubRecordMod {
	return StubRecordModFunc(func(_ context.Context, o *StubRecordTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m stubRecordMods) NameFunc(f func() string) StubRecordMod {
	return StubRecordModFunc(func(_ context.Context, o *StubRecordTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m stubRecordMods) UnsetName() StubRecordMod {
	return StubRecordModFunc(func(_ context.Context, o *StubRecordTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m stubRecordMods) RandomName(f *faker.Faker) StubRecordMod {
	return StubRecordModFunc(func(_ context.Context, o *StubRecordTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m stubRecordMods) CreatedAt(val time.Time) StubRecordMod {
	return StubRecordModFunc(func(_ context.Context, o *StubRecordTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m stubRecordMods) CreatedAtFunc(f func() time.Time) StubRecordMod {
	return StubRecordModFunc(func(_ context.Context, o *StubRecordTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m stubRecordMods) UnsetCreatedAt() StubRecordMod {
	return StubRecordModFunc(func(_ context.Context, o *StubRecordTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m stubRecordMods) RandomCreatedAt(f *faker.Faker) StubRecordMod {
	return StubRecordModFunc(func(_ context.Context, o *StubRecordTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m stubRecordMods) WithParentsCascading() StubRecordMod {
	return StubRecordModFunc(func(ctx context.Context, o *StubRecordTemplate) {
		if isDone, _ := stubRecordWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = stubRecordWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
