CREATE TABLE input_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  bucket TEXT NOT NULL,
  object_key TEXT NOT NULL,
  uri TEXT NOT NULL,
  format TEXT NOT NULL CHECK (format IN ('csv', 'parquet')),
  content_type TEXT,
  size_bytes BIGINT NOT NULL DEFAULT 0,
  etag TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT input_files_uri_unique UNIQUE (uri),
  CONSTRAINT input_files_bucket_object_key_unique UNIQUE (bucket, object_key)
);
