// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var InputFileErrors = &inputFileErrors{
	ErrUniqueInputFilesPkey: &UniqueConstraintError{
		schema:  "",
		table:   "input_files",
		columns: []string{"id"},
		s:       "input_files_pkey",
	},

	ErrUniqueInputFilesBucketObjectKeyUnique: &UniqueConstraintError{
		schema:  "",
		table:   "input_files",
		columns: []string{"bucket", "object_key"},
		s:       "input_files_bucket_object_key_unique",
	},

	ErrUniqueInputFilesUriUnique: &UniqueConstraintError{
		schema:  "",
		table:   "input_files",
		columns: []string{"uri"},
		s:       "input_files_uri_unique",
	},
}

type inputFileErrors struct {
	ErrUniqueInputFilesPkey *UniqueConstraintError

	ErrUniqueInputFilesBucketObjectKeyUnique *UniqueConstraintError

	ErrUniqueInputFilesUriUnique *UniqueConstraintError
}
