// Code generated by BobGen sql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var PipelineErrors = &pipelineErrors{
	ErrUniquePipelinesPkey: &UniqueConstraintError{
		schema:  "",
		table:   "pipelines",
		columns: []string{"id"},
		s:       "pipelines_pkey",
	},

	ErrUniquePipelinesPipelineIdUnique: &UniqueConstraintError{
		schema:  "",
		table:   "pipelines",
		columns: []string{"pipeline_id"},
		s:       "pipelines_pipeline_id_unique",
	},
}

type pipelineErrors struct {
	ErrUniquePipelinesPkey *UniqueConstraintError

	ErrUniquePipelinesPipelineIdUnique *UniqueConstraintError
}
