// Code generated by BobGen sql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

import (
	"context"
	"errors"
	"testing"

	"github.com/stephenafamo/bob"
	factory "go-transformer/internal/db/factory"
	models "go-transformer/internal/db/models"
)

func TestPipelineUniqueConstraintErrors(t *testing.T) {
	if testDB == nil {
		t.Skip("No database connection provided")
	}

	f := factory.New()
	tests := []struct {
		name         string
		expectedErr  *UniqueConstraintError
		conflictMods func(context.Context, *testing.T, bob.Executor, *models.Pipeline) factory.PipelineModSlice
	}{
		{
			name:        "ErrUniquePipelinesPkey",
			expectedErr: PipelineErrors.ErrUniquePipelinesPkey,
			conflictMods: func(ctx context.Context, t *testing.T, exec bob.Executor, obj *models.Pipeline) factory.PipelineModSlice {
				shouldUpdate := false
				updateMods := make(factory.PipelineModSlice, 0, 1)

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewPipelineWithContext(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.PipelineModSlice{
					factory.PipelineMods.ID(obj.ID),
				}
			},
		},
		{
			name:        "ErrUniquePipelinesPipelineIdUnique",
			expectedErr: PipelineErrors.ErrUniquePipelinesPipelineIdUnique,
			conflictMods: func(ctx context.Context, t *testing.T, exec bob.Executor, obj *models.Pipeline) factory.PipelineModSlice {
				shouldUpdate := false
				updateMods := make(factory.PipelineModSlice, 0, 1)

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewPipelineWithContext(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.PipelineModSlice{
					factory.PipelineMods.PipelineID(obj.PipelineID),
				}
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, cancel := context.WithCancel(t.Context())
			t.Cleanup(cancel)

			tx, err := testDB.Begin(ctx)
			if err != nil {
				t.Fatalf("Couldn't start database transaction: %v", err)
			}

			defer func() {
				if err := tx.Rollback(ctx); err != nil {
					t.Fatalf("Error rolling back transaction: %v", err)
				}
			}()

			var exec bob.Executor = tx

			obj, err := f.NewPipelineWithContext(ctx, factory.PipelineMods.WithParentsCascading()).Create(ctx, exec)
			if err != nil {
				t.Fatal(err)
			}

			obj2, err := f.NewPipelineWithContext(ctx).Create(ctx, exec)
			if err != nil {
				t.Fatal(err)
			}

			err = obj2.Update(ctx, exec, f.NewPipelineWithContext(ctx, tt.conflictMods(ctx, t, exec, obj)...).BuildSetter())
			if !errors.Is(ErrUniqueConstraint, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !errors.Is(tt.expectedErr, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.expectedErr.Error(), err)
			}
			if !ErrUniqueConstraint.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !tt.expectedErr.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.expectedErr.Error(), err)
			}
		})
	}
}
