// Code generated by BobGen sql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var StubRecordErrors = &stubRecordErrors{
	ErrUniqueStubRecordsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "stub_records",
		columns: []string{"id"},
		s:       "stub_records_pkey",
	},
}

type stubRecordErrors struct {
	ErrUniqueStubRecordsPkey *UniqueConstraintError
}
