// Code generated by BobGen sql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

// Make sure the type InputFile runs hooks after queries
var _ bob.HookableType = &InputFile{}

// Make sure the type Pipeline runs hooks after queries
var _ bob.HookableType = &Pipeline{}

// Make sure the type types.JSON[json.RawMessage] satisfies database/sql.Scanner
var _ sql.Scanner = (*types.JSON[json.RawMessage])(nil)

// Make sure the type types.JSON[json.RawMessage] satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(types.JSON[json.RawMessage])
