// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"encoding/json"
	"io"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/types"
)

// InputFile is an object representing the database table.
type InputFile struct {
	ID          int64                       `db:"id,pk" json:"id"`
	Name        string                      `db:"name" json:"name"`
	Bucket      string                      `db:"bucket" json:"bucket"`
	ObjectKey   string                      `db:"object_key" json:"object_key"`
	URI         string                      `db:"uri" json:"uri"`
	Format      string                      `db:"format" json:"format"`
	ContentType sql.Null[string]            `db:"content_type" json:"content_type"`
	SizeBytes   int64                       `db:"size_bytes" json:"size_bytes"`
	Etag        sql.Null[string]            `db:"etag" json:"etag"`
	Metadata    types.JSON[json.RawMessage] `db:"metadata" json:"metadata"`
	CreatedAt   time.Time                   `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time                   `db:"updated_at" json:"updated_at"`
}

// InputFileSlice is an alias for a slice of pointers to InputFile.
// This should almost always be used instead of []*InputFile.
type InputFileSlice []*InputFile

// InputFiles contains methods to work with the input_files table
var InputFiles = psql.NewTablex[*InputFile, InputFileSlice, *InputFileSetter]("", "input_files", buildInputFileColumns("input_files"))

// InputFilesQuery is a query on the input_files table
type InputFilesQuery = *psql.ViewQuery[*InputFile, InputFileSlice]

func buildInputFileColumns(tableName string) inputFileColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "name", "bucket", "object_key", "uri", "format", "content_type", "size_bytes", "etag", "metadata", "created_at", "updated_at",
	)
	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}
	return inputFileColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          psql.Quote(tableName, "id"),
		Name:        psql.Quote(tableName, "name"),
		Bucket:      psql.Quote(tableName, "bucket"),
		ObjectKey:   psql.Quote(tableName, "object_key"),
		URI:         psql.Quote(tableName, "uri"),
		Format:      psql.Quote(tableName, "format"),
		ContentType: psql.Quote(tableName, "content_type"),
		SizeBytes:   psql.Quote(tableName, "size_bytes"),
		Etag:        psql.Quote(tableName, "etag"),
		Metadata:    psql.Quote(tableName, "metadata"),
		CreatedAt:   psql.Quote(tableName, "created_at"),
		UpdatedAt:   psql.Quote(tableName, "updated_at"),
	}
}

type inputFileColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          psql.Expression
	Name        psql.Expression
	Bucket      psql.Expression
	ObjectKey   psql.Expression
	URI         psql.Expression
	Format      psql.Expression
	ContentType psql.Expression
	SizeBytes   psql.Expression
	Etag        psql.Expression
	Metadata    psql.Expression
	CreatedAt   psql.Expression
	UpdatedAt   psql.Expression
}

func (c inputFileColumns) Alias() string {
	return c.tableAlias
}

func (inputFileColumns) AliasedAs(tableName string) inputFileColumns {
	return buildInputFileColumns(tableName)
}

func (c inputFileColumns) Unqualified() inputFileColumns {
	return buildInputFileColumns("")
}

// InputFileSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type InputFileSetter struct {
	ID          *int64                       `db:"id,pk" json:"id"`
	Name        *string                      `db:"name" json:"name"`
	Bucket      *string                      `db:"bucket" json:"bucket"`
	ObjectKey   *string                      `db:"object_key" json:"object_key"`
	URI         *string                      `db:"uri" json:"uri"`
	Format      *string                      `db:"format" json:"format"`
	ContentType *sql.Null[string]            `db:"content_type" json:"content_type"`
	SizeBytes   *int64                       `db:"size_bytes" json:"size_bytes"`
	Etag        *sql.Null[string]            `db:"etag" json:"etag"`
	Metadata    *types.JSON[json.RawMessage] `db:"metadata" json:"metadata"`
	CreatedAt   *time.Time                   `db:"created_at" json:"created_at"`
	UpdatedAt   *time.Time                   `db:"updated_at" json:"updated_at"`
}

func (s InputFileSetter) SetColumns() []string {
	vals := make([]string, 0, 12)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.Name != nil {
		vals = append(vals, "name")
	}
	if s.Bucket != nil {
		vals = append(vals, "bucket")
	}
	if s.ObjectKey != nil {
		vals = append(vals, "object_key")
	}
	if s.URI != nil {
		vals = append(vals, "uri")
	}
	if s.Format != nil {
		vals = append(vals, "format")
	}
	if s.ContentType != nil {
		vals = append(vals, "content_type")
	}
	if s.SizeBytes != nil {
		vals = append(vals, "size_bytes")
	}
	if s.Etag != nil {
		vals = append(vals, "etag")
	}
	if s.Metadata != nil {
		vals = append(vals, "metadata")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s InputFileSetter) Overwrite(t *InputFile) {
	if s.ID != nil {
		t.ID = func() int64 {
			if s.ID == nil {
				return *new(int64)
			}
			return *s.ID
		}()
	}
	if s.Name != nil {
		t.Name = func() string {
			if s.Name == nil {
				return *new(string)
			}
			return *s.Name
		}()
	}
	if s.Bucket != nil {
		t.Bucket = func() string {
			if s.Bucket == nil {
				return *new(string)
			}
			return *s.Bucket
		}()
	}
	if s.ObjectKey != nil {
		t.ObjectKey = func() string {
			if s.ObjectKey == nil {
				return *new(string)
			}
			return *s.ObjectKey
		}()
	}
	if s.URI != nil {
		t.URI = func() string {
			if s.URI == nil {
				return *new(string)
			}
			return *s.URI
		}()
	}
	if s.Format != nil {
		t.Format = func() string {
			if s.Format == nil {
				return *new(string)
			}
			return *s.Format
		}()
	}
	if s.ContentType != nil {
		t.ContentType = func() sql.Null[string] {
			if s.ContentType == nil {
				return *new(sql.Null[string])
			}
			v := s.ContentType
			return *v
		}()
	}
	if s.SizeBytes != nil {
		t.SizeBytes = func() int64 {
			if s.SizeBytes == nil {
				return *new(int64)
			}
			return *s.SizeBytes
		}()
	}
	if s.Etag != nil {
		t.Etag = func() sql.Null[string] {
			if s.Etag == nil {
				return *new(sql.Null[string])
			}
			v := s.Etag
			return *v
		}()
	}
	if s.Metadata != nil {
		t.Metadata = func() types.JSON[json.RawMessage] {
			if s.Metadata == nil {
				return *new(types.JSON[json.RawMessage])
			}
			return *s.Metadata
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() time.Time {
			if s.CreatedAt == nil {
				return *new(time.Time)
			}
			return *s.CreatedAt
		}()
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = func() time.Time {
			if s.UpdatedAt == nil {
				return *new(time.Time)
			}
			return *s.UpdatedAt
		}()
	}
}

func (s *InputFileSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return InputFiles.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 12)
		if s.ID != nil {
			vals[0] = psql.Arg(func() int64 {
				if s.ID == nil {
					return *new(int64)
				}
				return *s.ID
			}())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name != nil {
			vals[1] = psql.Arg(func() string {
				if s.Name == nil {
					return *new(string)
				}
				return *s.Name
			}())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Bucket != nil {
			vals[2] = psql.Arg(func() string {
				if s.Bucket == nil {
					return *new(string)
				}
				return *s.Bucket
			}())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.ObjectKey != nil {
			vals[3] = psql.Arg(func() string {
				if s.ObjectKey == nil {
					return *new(string)
				}
				return *s.ObjectKey
			}())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.URI != nil {
			vals[4] = psql.Arg(func() string {
				if s.URI == nil {
					return *new(string)
				}
				return *s.URI
			}())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.Format != nil {
			vals[5] = psql.Arg(func() string {
				if s.Format == nil {
					return *new(string)
				}
				return *s.Format
			}())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.ContentType != nil {
			vals[6] = psql.Arg(func() sql.Null[string] {
				if s.ContentType == nil {
					return *new(sql.Null[string])
				}
				v := s.ContentType
				return *v
			}())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.SizeBytes != nil {
			vals[7] = psql.Arg(func() int64 {
				if s.SizeBytes == nil {
					return *new(int64)
				}
				return *s.SizeBytes
			}())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.Etag != nil {
			vals[8] = psql.Arg(func() sql.Null[string] {
				if s.Etag == nil {
					return *new(sql.Null[string])
				}
				v := s.Etag
				return *v
			}())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if s.Metadata != nil {
			vals[9] = psql.Arg(func() types.JSON[json.RawMessage] {
				if s.Metadata == nil {
					return *new(types.JSON[json.RawMessage])
				}
				return *s.Metadata
			}())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt != nil {
			vals[10] = psql.Arg(func() time.Time {
				if s.CreatedAt == nil {
					return *new(time.Time)
				}
				return *s.CreatedAt
			}())
		} else {
			vals[10] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt != nil {
			vals[11] = psql.Arg(func() time.Time {
				if s.UpdatedAt == nil {
					return *new(time.Time)
				}
				return *s.UpdatedAt
			}())
		} else {
			vals[11] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s InputFileSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s InputFileSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 12)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Bucket != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "bucket")...),
			psql.Arg(s.Bucket),
		}})
	}

	if s.ObjectKey != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "object_key")...),
			psql.Arg(s.ObjectKey),
		}})
	}

	if s.URI != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "uri")...),
			psql.Arg(s.URI),
		}})
	}

	if s.Format != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "format")...),
			psql.Arg(s.Format),
		}})
	}

	if s.ContentType != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "content_type")...),
			psql.Arg(s.ContentType),
		}})
	}

	if s.SizeBytes != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "size_bytes")...),
			psql.Arg(s.SizeBytes),
		}})
	}

	if s.Etag != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "etag")...),
			psql.Arg(s.Etag),
		}})
	}

	if s.Metadata != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "metadata")...),
			psql.Arg(s.Metadata),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindInputFile retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindInputFile(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*InputFile, error) {
	if len(cols) == 0 {
		return InputFiles.Query(
			sm.Where(InputFiles.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return InputFiles.Query(
		sm.Where(InputFiles.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(InputFiles.Columns.Only(cols...)),
	).One(ctx, exec)
}

// InputFileExists checks the presence of a single record by primary key
func InputFileExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return InputFiles.Query(
		sm.Where(InputFiles.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after InputFile is retrieved from the database
func (o *InputFile) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = InputFiles.AfterSelectHooks.RunHooks(ctx, exec, InputFileSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = InputFiles.AfterInsertHooks.RunHooks(ctx, exec, InputFileSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = InputFiles.AfterUpdateHooks.RunHooks(ctx, exec, InputFileSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = InputFiles.AfterDeleteHooks.RunHooks(ctx, exec, InputFileSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = InputFiles.AfterMergeHooks.RunHooks(ctx, exec, InputFileSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the InputFile
func (o *InputFile) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *InputFile) pkEQ() dialect.Expression {
	return psql.Quote("input_files", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the InputFile
func (o *InputFile) Update(ctx context.Context, exec bob.Executor, s *InputFileSetter) error {
	v, err := InputFiles.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single InputFile record with an executor
func (o *InputFile) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := InputFiles.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the InputFile using the executor
func (o *InputFile) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := InputFiles.Query(
		sm.Where(InputFiles.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after InputFileSlice is retrieved from the database
func (o InputFileSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = InputFiles.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = InputFiles.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = InputFiles.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = InputFiles.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = InputFiles.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o InputFileSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("input_files", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o InputFileSlice) copyMatchingRows(from ...*InputFile) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o InputFileSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return InputFiles.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *InputFile:
				o.copyMatchingRows(retrieved)
			case []*InputFile:
				o.copyMatchingRows(retrieved...)
			case InputFileSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a InputFile or a slice of InputFile
				// then run the AfterUpdateHooks on the slice
				_, err = InputFiles.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o InputFileSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return InputFiles.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *InputFile:
				o.copyMatchingRows(retrieved)
			case []*InputFile:
				o.copyMatchingRows(retrieved...)
			case InputFileSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a InputFile or a slice of InputFile
				// then run the AfterDeleteHooks on the slice
				_, err = InputFiles.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o InputFileSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return InputFiles.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *InputFile:
				o.copyMatchingRows(retrieved)
			case []*InputFile:
				o.copyMatchingRows(retrieved...)
			case InputFileSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a InputFile or a slice of InputFile
				// then run the AfterMergeHooks on the slice
				_, err = InputFiles.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o InputFileSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals InputFileSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := InputFiles.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o InputFileSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := InputFiles.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o InputFileSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := InputFiles.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type inputFileWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, int64]
	Name        psql.WhereMod[Q, string]
	Bucket      psql.WhereMod[Q, string]
	ObjectKey   psql.WhereMod[Q, string]
	URI         psql.WhereMod[Q, string]
	Format      psql.WhereMod[Q, string]
	ContentType psql.WhereNullMod[Q, string]
	SizeBytes   psql.WhereMod[Q, int64]
	Etag        psql.WhereNullMod[Q, string]
	Metadata    psql.WhereMod[Q, types.JSON[json.RawMessage]]
	CreatedAt   psql.WhereMod[Q, time.Time]
	UpdatedAt   psql.WhereMod[Q, time.Time]
}

func (inputFileWhere[Q]) AliasedAs(alias string) inputFileWhere[Q] {
	return buildInputFileWhere[Q](buildInputFileColumns(alias))
}

func buildInputFileWhere[Q psql.Filterable](cols inputFileColumns) inputFileWhere[Q] {
	return inputFileWhere[Q]{
		ID:          psql.Where[Q, int64](cols.ID),
		Name:        psql.Where[Q, string](cols.Name),
		Bucket:      psql.Where[Q, string](cols.Bucket),
		ObjectKey:   psql.Where[Q, string](cols.ObjectKey),
		URI:         psql.Where[Q, string](cols.URI),
		Format:      psql.Where[Q, string](cols.Format),
		ContentType: psql.WhereNull[Q, string](cols.ContentType),
		SizeBytes:   psql.Where[Q, int64](cols.SizeBytes),
		Etag:        psql.WhereNull[Q, string](cols.Etag),
		Metadata:    psql.Where[Q, types.JSON[json.RawMessage]](cols.Metadata),
		CreatedAt:   psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:   psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}
