// Code generated by BobGen sql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"encoding/json"
	"io"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/types"
)

// Pipeline is an object representing the database table.
type Pipeline struct {
	ID              int64                                 `db:"id,pk" json:"id"`
	Name            string                                `db:"name" json:"name"`
	PipelineID      string                                `db:"pipeline_id" json:"pipeline_id"`
	Version         int32                                 `db:"version" json:"version"`
	Spec            types.JSON[json.RawMessage]           `db:"spec" json:"spec"`
	Status          string                                `db:"status" json:"status"`
	ValidationError sql.Null[types.JSON[json.RawMessage]] `db:"validation_error" json:"validation_error"`
	ActivatedAt     sql.Null[time.Time]                   `db:"activated_at" json:"activated_at"`
	CreatedAt       time.Time                             `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time                             `db:"updated_at" json:"updated_at"`
}

// PipelineSlice is an alias for a slice of pointers to Pipeline.
// This should almost always be used instead of []*Pipeline.
type PipelineSlice []*Pipeline

// Pipelines contains methods to work with the pipelines table
var Pipelines = psql.NewTablex[*Pipeline, PipelineSlice, *PipelineSetter]("", "pipelines", buildPipelineColumns("pipelines"))

// PipelinesQuery is a query on the pipelines table
type PipelinesQuery = *psql.ViewQuery[*Pipeline, PipelineSlice]

func buildPipelineColumns(tableName string) pipelineColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "name", "pipeline_id", "version", "spec", "status", "validation_error", "activated_at", "created_at", "updated_at",
	)
	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}
	return pipelineColumns{
		ColumnsExpr:     columnsExpr,
		tableAlias:      tableName,
		ID:              psql.Quote(tableName, "id"),
		Name:            psql.Quote(tableName, "name"),
		PipelineID:      psql.Quote(tableName, "pipeline_id"),
		Version:         psql.Quote(tableName, "version"),
		Spec:            psql.Quote(tableName, "spec"),
		Status:          psql.Quote(tableName, "status"),
		ValidationError: psql.Quote(tableName, "validation_error"),
		ActivatedAt:     psql.Quote(tableName, "activated_at"),
		CreatedAt:       psql.Quote(tableName, "created_at"),
		UpdatedAt:       psql.Quote(tableName, "updated_at"),
	}
}

type pipelineColumns struct {
	expr.ColumnsExpr
	tableAlias      string
	ID              psql.Expression
	Name            psql.Expression
	PipelineID      psql.Expression
	Version         psql.Expression
	Spec            psql.Expression
	Status          psql.Expression
	ValidationError psql.Expression
	ActivatedAt     psql.Expression
	CreatedAt       psql.Expression
	UpdatedAt       psql.Expression
}

func (c pipelineColumns) Alias() string {
	return c.tableAlias
}

func (pipelineColumns) AliasedAs(tableName string) pipelineColumns {
	return buildPipelineColumns(tableName)
}

func (c pipelineColumns) Unqualified() pipelineColumns {
	return buildPipelineColumns("")
}

// PipelineSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type PipelineSetter struct {
	ID              *int64                                 `db:"id,pk" json:"id"`
	Name            *string                                `db:"name" json:"name"`
	PipelineID      *string                                `db:"pipeline_id" json:"pipeline_id"`
	Version         *int32                                 `db:"version" json:"version"`
	Spec            *types.JSON[json.RawMessage]           `db:"spec" json:"spec"`
	Status          *string                                `db:"status" json:"status"`
	ValidationError *sql.Null[types.JSON[json.RawMessage]] `db:"validation_error" json:"validation_error"`
	ActivatedAt     *sql.Null[time.Time]                   `db:"activated_at" json:"activated_at"`
	CreatedAt       *time.Time                             `db:"created_at" json:"created_at"`
	UpdatedAt       *time.Time                             `db:"updated_at" json:"updated_at"`
}

func (s PipelineSetter) SetColumns() []string {
	vals := make([]string, 0, 10)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.Name != nil {
		vals = append(vals, "name")
	}
	if s.PipelineID != nil {
		vals = append(vals, "pipeline_id")
	}
	if s.Version != nil {
		vals = append(vals, "version")
	}
	if s.Spec != nil {
		vals = append(vals, "spec")
	}
	if s.Status != nil {
		vals = append(vals, "status")
	}
	if s.ValidationError != nil {
		vals = append(vals, "validation_error")
	}
	if s.ActivatedAt != nil {
		vals = append(vals, "activated_at")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s PipelineSetter) Overwrite(t *Pipeline) {
	if s.ID != nil {
		t.ID = func() int64 {
			if s.ID == nil {
				return *new(int64)
			}
			return *s.ID
		}()
	}
	if s.Name != nil {
		t.Name = func() string {
			if s.Name == nil {
				return *new(string)
			}
			return *s.Name
		}()
	}
	if s.PipelineID != nil {
		t.PipelineID = func() string {
			if s.PipelineID == nil {
				return *new(string)
			}
			return *s.PipelineID
		}()
	}
	if s.Version != nil {
		t.Version = func() int32 {
			if s.Version == nil {
				return *new(int32)
			}
			return *s.Version
		}()
	}
	if s.Spec != nil {
		t.Spec = func() types.JSON[json.RawMessage] {
			if s.Spec == nil {
				return *new(types.JSON[json.RawMessage])
			}
			return *s.Spec
		}()
	}
	if s.Status != nil {
		t.Status = func() string {
			if s.Status == nil {
				return *new(string)
			}
			return *s.Status
		}()
	}
	if s.ValidationError != nil {
		t.ValidationError = func() sql.Null[types.JSON[json.RawMessage]] {
			if s.ValidationError == nil {
				return *new(sql.Null[types.JSON[json.RawMessage]])
			}
			v := s.ValidationError
			return *v
		}()
	}
	if s.ActivatedAt != nil {
		t.ActivatedAt = func() sql.Null[time.Time] {
			if s.ActivatedAt == nil {
				return *new(sql.Null[time.Time])
			}
			v := s.ActivatedAt
			return *v
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() time.Time {
			if s.CreatedAt == nil {
				return *new(time.Time)
			}
			return *s.CreatedAt
		}()
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = func() time.Time {
			if s.UpdatedAt == nil {
				return *new(time.Time)
			}
			return *s.UpdatedAt
		}()
	}
}

func (s *PipelineSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Pipelines.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 10)
		if s.ID != nil {
			vals[0] = psql.Arg(func() int64 {
				if s.ID == nil {
					return *new(int64)
				}
				return *s.ID
			}())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name != nil {
			vals[1] = psql.Arg(func() string {
				if s.Name == nil {
					return *new(string)
				}
				return *s.Name
			}())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.PipelineID != nil {
			vals[2] = psql.Arg(func() string {
				if s.PipelineID == nil {
					return *new(string)
				}
				return *s.PipelineID
			}())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Version != nil {
			vals[3] = psql.Arg(func() int32 {
				if s.Version == nil {
					return *new(int32)
				}
				return *s.Version
			}())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Spec != nil {
			vals[4] = psql.Arg(func() types.JSON[json.RawMessage] {
				if s.Spec == nil {
					return *new(types.JSON[json.RawMessage])
				}
				return *s.Spec
			}())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.Status != nil {
			vals[5] = psql.Arg(func() string {
				if s.Status == nil {
					return *new(string)
				}
				return *s.Status
			}())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.ValidationError != nil {
			vals[6] = psql.Arg(func() sql.Null[types.JSON[json.RawMessage]] {
				if s.ValidationError == nil {
					return *new(sql.Null[types.JSON[json.RawMessage]])
				}
				v := s.ValidationError
				return *v
			}())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.ActivatedAt != nil {
			vals[7] = psql.Arg(func() sql.Null[time.Time] {
				if s.ActivatedAt == nil {
					return *new(sql.Null[time.Time])
				}
				v := s.ActivatedAt
				return *v
			}())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt != nil {
			vals[8] = psql.Arg(func() time.Time {
				if s.CreatedAt == nil {
					return *new(time.Time)
				}
				return *s.CreatedAt
			}())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt != nil {
			vals[9] = psql.Arg(func() time.Time {
				if s.UpdatedAt == nil {
					return *new(time.Time)
				}
				return *s.UpdatedAt
			}())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s PipelineSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s PipelineSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 10)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.PipelineID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "pipeline_id")...),
			psql.Arg(s.PipelineID),
		}})
	}

	if s.Version != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "version")...),
			psql.Arg(s.Version),
		}})
	}

	if s.Spec != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "spec")...),
			psql.Arg(s.Spec),
		}})
	}

	if s.Status != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "status")...),
			psql.Arg(s.Status),
		}})
	}

	if s.ValidationError != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "validation_error")...),
			psql.Arg(s.ValidationError),
		}})
	}

	if s.ActivatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "activated_at")...),
			psql.Arg(s.ActivatedAt),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindPipeline retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindPipeline(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Pipeline, error) {
	if len(cols) == 0 {
		return Pipelines.Query(
			sm.Where(Pipelines.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Pipelines.Query(
		sm.Where(Pipelines.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Pipelines.Columns.Only(cols...)),
	).One(ctx, exec)
}

// PipelineExists checks the presence of a single record by primary key
func PipelineExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Pipelines.Query(
		sm.Where(Pipelines.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Pipeline is retrieved from the database
func (o *Pipeline) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Pipelines.AfterSelectHooks.RunHooks(ctx, exec, PipelineSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Pipelines.AfterInsertHooks.RunHooks(ctx, exec, PipelineSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Pipelines.AfterUpdateHooks.RunHooks(ctx, exec, PipelineSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Pipelines.AfterDeleteHooks.RunHooks(ctx, exec, PipelineSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = Pipelines.AfterMergeHooks.RunHooks(ctx, exec, PipelineSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Pipeline
func (o *Pipeline) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Pipeline) pkEQ() dialect.Expression {
	return psql.Quote("pipelines", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Pipeline
func (o *Pipeline) Update(ctx context.Context, exec bob.Executor, s *PipelineSetter) error {
	v, err := Pipelines.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single Pipeline record with an executor
func (o *Pipeline) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Pipelines.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Pipeline using the executor
func (o *Pipeline) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Pipelines.Query(
		sm.Where(Pipelines.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after PipelineSlice is retrieved from the database
func (o PipelineSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Pipelines.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Pipelines.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Pipelines.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Pipelines.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = Pipelines.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o PipelineSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("pipelines", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o PipelineSlice) copyMatchingRows(from ...*Pipeline) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o PipelineSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Pipelines.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Pipeline:
				o.copyMatchingRows(retrieved)
			case []*Pipeline:
				o.copyMatchingRows(retrieved...)
			case PipelineSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Pipeline or a slice of Pipeline
				// then run the AfterUpdateHooks on the slice
				_, err = Pipelines.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o PipelineSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Pipelines.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Pipeline:
				o.copyMatchingRows(retrieved)
			case []*Pipeline:
				o.copyMatchingRows(retrieved...)
			case PipelineSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Pipeline or a slice of Pipeline
				// then run the AfterDeleteHooks on the slice
				_, err = Pipelines.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o PipelineSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Pipelines.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Pipeline:
				o.copyMatchingRows(retrieved)
			case []*Pipeline:
				o.copyMatchingRows(retrieved...)
			case PipelineSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Pipeline or a slice of Pipeline
				// then run the AfterMergeHooks on the slice
				_, err = Pipelines.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o PipelineSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals PipelineSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Pipelines.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o PipelineSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Pipelines.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o PipelineSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Pipelines.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type pipelineWhere[Q psql.Filterable] struct {
	ID              psql.WhereMod[Q, int64]
	Name            psql.WhereMod[Q, string]
	PipelineID      psql.WhereMod[Q, string]
	Version         psql.WhereMod[Q, int32]
	Spec            psql.WhereMod[Q, types.JSON[json.RawMessage]]
	Status          psql.WhereMod[Q, string]
	ValidationError psql.WhereNullMod[Q, types.JSON[json.RawMessage]]
	ActivatedAt     psql.WhereNullMod[Q, time.Time]
	CreatedAt       psql.WhereMod[Q, time.Time]
	UpdatedAt       psql.WhereMod[Q, time.Time]
}

func (pipelineWhere[Q]) AliasedAs(alias string) pipelineWhere[Q] {
	return buildPipelineWhere[Q](buildPipelineColumns(alias))
}

func buildPipelineWhere[Q psql.Filterable](cols pipelineColumns) pipelineWhere[Q] {
	return pipelineWhere[Q]{
		ID:              psql.Where[Q, int64](cols.ID),
		Name:            psql.Where[Q, string](cols.Name),
		PipelineID:      psql.Where[Q, string](cols.PipelineID),
		Version:         psql.Where[Q, int32](cols.Version),
		Spec:            psql.Where[Q, types.JSON[json.RawMessage]](cols.Spec),
		Status:          psql.Where[Q, string](cols.Status),
		ValidationError: psql.WhereNull[Q, types.JSON[json.RawMessage]](cols.ValidationError),
		ActivatedAt:     psql.WhereNull[Q, time.Time](cols.ActivatedAt),
		CreatedAt:       psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:       psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}
