// Code generated by BobGen sql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// StubRecord is an object representing the database table.
type StubRecord struct {
	ID        int64     `db:"id,pk" json:"id"`
	Name      string    `db:"name" json:"name"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

// StubRecordSlice is an alias for a slice of pointers to StubRecord.
// This should almost always be used instead of []*StubRecord.
type StubRecordSlice []*StubRecord

// StubRecords contains methods to work with the stub_records table
var StubRecords = psql.NewTablex[*StubRecord, StubRecordSlice, *StubRecordSetter]("", "stub_records", buildStubRecordColumns("stub_records"))

// StubRecordsQuery is a query on the stub_records table
type StubRecordsQuery = *psql.ViewQuery[*StubRecord, StubRecordSlice]

func buildStubRecordColumns(tableName string) stubRecordColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "name", "created_at",
	)
	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}
	return stubRecordColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          psql.Quote(tableName, "id"),
		Name:        psql.Quote(tableName, "name"),
		CreatedAt:   psql.Quote(tableName, "created_at"),
	}
}

type stubRecordColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	Name       psql.Expression
	CreatedAt  psql.Expression
}

func (c stubRecordColumns) Alias() string {
	return c.tableAlias
}

func (stubRecordColumns) AliasedAs(tableName string) stubRecordColumns {
	return buildStubRecordColumns(tableName)
}

func (c stubRecordColumns) Unqualified() stubRecordColumns {
	return buildStubRecordColumns("")
}

// StubRecordSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type StubRecordSetter struct {
	ID        *int64     `db:"id,pk" json:"id"`
	Name      *string    `db:"name" json:"name"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}

func (s StubRecordSetter) SetColumns() []string {
	vals := make([]string, 0, 3)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.Name != nil {
		vals = append(vals, "name")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	return vals
}

func (s StubRecordSetter) Overwrite(t *StubRecord) {
	if s.ID != nil {
		t.ID = func() int64 {
			if s.ID == nil {
				return *new(int64)
			}
			return *s.ID
		}()
	}
	if s.Name != nil {
		t.Name = func() string {
			if s.Name == nil {
				return *new(string)
			}
			return *s.Name
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() time.Time {
			if s.CreatedAt == nil {
				return *new(time.Time)
			}
			return *s.CreatedAt
		}()
	}
}

func (s *StubRecordSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return StubRecords.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 3)
		if s.ID != nil {
			vals[0] = psql.Arg(func() int64 {
				if s.ID == nil {
					return *new(int64)
				}
				return *s.ID
			}())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name != nil {
			vals[1] = psql.Arg(func() string {
				if s.Name == nil {
					return *new(string)
				}
				return *s.Name
			}())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt != nil {
			vals[2] = psql.Arg(func() time.Time {
				if s.CreatedAt == nil {
					return *new(time.Time)
				}
				return *s.CreatedAt
			}())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s StubRecordSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s StubRecordSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 3)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// FindStubRecord retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindStubRecord(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*StubRecord, error) {
	if len(cols) == 0 {
		return StubRecords.Query(
			sm.Where(StubRecords.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return StubRecords.Query(
		sm.Where(StubRecords.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(StubRecords.Columns.Only(cols...)),
	).One(ctx, exec)
}

// StubRecordExists checks the presence of a single record by primary key
func StubRecordExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return StubRecords.Query(
		sm.Where(StubRecords.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after StubRecord is retrieved from the database
func (o *StubRecord) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = StubRecords.AfterSelectHooks.RunHooks(ctx, exec, StubRecordSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = StubRecords.AfterInsertHooks.RunHooks(ctx, exec, StubRecordSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = StubRecords.AfterUpdateHooks.RunHooks(ctx, exec, StubRecordSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = StubRecords.AfterDeleteHooks.RunHooks(ctx, exec, StubRecordSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = StubRecords.AfterMergeHooks.RunHooks(ctx, exec, StubRecordSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the StubRecord
func (o *StubRecord) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *StubRecord) pkEQ() dialect.Expression {
	return psql.Quote("stub_records", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the StubRecord
func (o *StubRecord) Update(ctx context.Context, exec bob.Executor, s *StubRecordSetter) error {
	v, err := StubRecords.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single StubRecord record with an executor
func (o *StubRecord) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := StubRecords.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the StubRecord using the executor
func (o *StubRecord) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := StubRecords.Query(
		sm.Where(StubRecords.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after StubRecordSlice is retrieved from the database
func (o StubRecordSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = StubRecords.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = StubRecords.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = StubRecords.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = StubRecords.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = StubRecords.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o StubRecordSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("stub_records", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o StubRecordSlice) copyMatchingRows(from ...*StubRecord) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o StubRecordSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return StubRecords.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *StubRecord:
				o.copyMatchingRows(retrieved)
			case []*StubRecord:
				o.copyMatchingRows(retrieved...)
			case StubRecordSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a StubRecord or a slice of StubRecord
				// then run the AfterUpdateHooks on the slice
				_, err = StubRecords.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o StubRecordSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return StubRecords.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *StubRecord:
				o.copyMatchingRows(retrieved)
			case []*StubRecord:
				o.copyMatchingRows(retrieved...)
			case StubRecordSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a StubRecord or a slice of StubRecord
				// then run the AfterDeleteHooks on the slice
				_, err = StubRecords.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o StubRecordSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return StubRecords.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *StubRecord:
				o.copyMatchingRows(retrieved)
			case []*StubRecord:
				o.copyMatchingRows(retrieved...)
			case StubRecordSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a StubRecord or a slice of StubRecord
				// then run the AfterMergeHooks on the slice
				_, err = StubRecords.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o StubRecordSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals StubRecordSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := StubRecords.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o StubRecordSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := StubRecords.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o StubRecordSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := StubRecords.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type stubRecordWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, int64]
	Name      psql.WhereMod[Q, string]
	CreatedAt psql.WhereMod[Q, time.Time]
}

func (stubRecordWhere[Q]) AliasedAs(alias string) stubRecordWhere[Q] {
	return buildStubRecordWhere[Q](buildStubRecordColumns(alias))
}

func buildStubRecordWhere[Q psql.Filterable](cols stubRecordColumns) stubRecordWhere[Q] {
	return stubRecordWhere[Q]{
		ID:        psql.Where[Q, int64](cols.ID),
		Name:      psql.Where[Q, string](cols.Name),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt),
	}
}
